package com.techofgrowth.learnhtml;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.cardview.widget.CardView;

import android.content.Intent;
import android.os.Bundle;
import android.view.MenuItem;
import android.widget.TextView;

public class card3_activity extends AppCompatActivity {
Toolbar toolbar;
String t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20,t21,t22,t23,t24,t25,t26,t27,t28,t29,t30;
String t31,t32,t33,t34,t35,t36,t37,t38,t39,t40,t41,t42,t43,t44,t45,t46,t47,t48,t49,t50,t51,t52,t53,t54,t55,t56,t57,t58,t59,t60;
String t61,t62,t63,t64,t65,t66,t67,t68,t69,t70,t71,t72,t73,t74,t75,t76,t77,t78,t79,t80,t81,t82,t83,t84,t85,t86,t87,t88,t89,t90;
String t91,t92,t93,t94,t95,t96,t97;


TextView txt1,txt2,txt3,txt4,txt5,txt6,txt7,txt8,txt9,txt10,txt11,txt12,txt13,txt14,txt15,txt16,txt17,txt18,txt19,txt20;
TextView txt21,txt22,txt23,txt24,txt25,txt26,txt27,txt28,txt29,txt30,txt31,txt32,txt33,txt34,txt35,txt36,txt37,txt38,txt39,txt40;
TextView txt41,txt42,txt43,txt44,txt45,txt46,txt47,txt48,txt49,txt50,txt51,txt52,txt53,txt54,txt55,txt56,txt57,txt58,txt59,txt60;
TextView txt61,txt62,txt63,txt64,txt65,txt66,txt67,txt68,txt69,txt70,txt71,txt72,txt73,txt74,txt75,txt76,txt77,txt78,txt79,txt80;
TextView txt81,txt82,txt83,txt84,txt85,txt86,txt87,txt88,txt89,txt90,txt91,txt92,txt93,txt94,txt95,txt96,txt97;

CardView card1,card2,card3,card4,card5,card6,card7,card8,card9,card10;
CardView card11,card12,card13,card14,card15,card16,card17,card18,card19,card20;
CardView card21,card22,card23,card24,card25,card26,card27,card28,card29,card30;
CardView card31,card32,card33,card34,card35,card36,card37,card38,card39,card40;
CardView card41,card42,card43,card44,card45,card46,card47,card48,card49,card50;
CardView card51,card52,card53,card54,card55,card56,card57,card58,card59,card60;
CardView card61,card62,card63,card64,card65,card66,card67,card68,card69,card70;
CardView card71,card72,card73,card74,card75,card76,card77,card78,card79,card80;
CardView card81,card82,card83,card84,card85,card86,card87,card88,card89,card90;
CardView card91,card92,card93,card94,card95,card96,card97;




String file1, file2,file3,file4,file5,file6,file7,file8,file9,file10;
String file11, file12,file13,file14,file15,file16,file17,file18,file19,file20;
String file21, file22,file23,file24,file25,file26,file27,file28,file29,file30;
String file31, file32,file33,file34,file35,file36,file37,file38,file39,file40;
String file41, file42,file43,file44,file45,file46,file47,file48,file49,file50;
String file51, file52,file53,file54,file55,file56,file57,file58,file59,file60;
String file61, file62,file63,file64,file65,file66,file67,file68,file69,file70;
String file71, file72,file73,file74,file75,file76,file77,file78,file79,file80;
String file81, file82,file83,file84,file85,file86,file87,file88,file89,file90;
String file91, file92,file93,file94,file95,file96,file97;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_card3);


        //ToolBar
        toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        getSupportActionBar().setTitle("");
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);


        t1 = "HTML <!DOCTYPE> tag";
        t2 = "HTML Anchor";
        t3 = "HTML <abbr> tag";
        t4 = "HTML <acronym> tag";
        t5 = "HTML <address> tag";
        t6 = "HTML <applet> tag";
        t7 = "HTML <area> tag";
        t8 = "HTML Article Tag";
        t9 = "HTML Aside Tag";
        t10 = "HTML Audio Tag";
        t11 = "HTML Bold Tag";
        t12 = "HTML <base> tag";
        t13 = "HTML <basefont> tag";
        t14 = "HTML <bdi> tag";
        t15 = "HTML <bdo> tag";
        t16 = "HTML <big> tag";
        t17 = "HTML <blockquote> tag";
        t18 = "HTML <body> tag";
        t19 = "HTML <br> tag";
        t20 = "HTML Button Tag";
        t21 = "HTML Canvas Tag";
        t22 = "HTML <caption> tag";
        t23 = "HTML <center> tag";
        t24 = "HTML <cite> tag";
        t25 = "HTML Code Tag";
        t26 = "HTML <col> tag";
        t27 = "HTML <colgroup> tag";
        t28 = "HTML Data Tag";
        t29 = "HTML Datalist Tag";
        t30 = "HTML Description List";
        t31 = "HTML <del> tag";
        t32 = "HTML Details Tag";
        t33 = "HTML <dfn> tag";
        t34 = "HTML Dialog Tag";
        t35 = "HTML <dir> tag";
        t36 = "HTML Div Tag";
        t37 = "HTML <em> tag";
        t38 = "HTML <embed> tag";
        t39 = "HTML <fieldset> tag";
        t40 = "HTML figcaption tag";
        t41 = "HTML figure tag";
        t42 = "HTML <font> tag";
        t43 = "HTML Footer Tag";
        t44 = "HTML Form Tag";
        t45 = "HTML <frame> tag";
        t46 = "HTML <frameset> tag";
        t47 = "HTML Heading";
        t48 = "HTML Head";
        t49 = "HTML Header Tag";
        t50 = "HTML hr tag";
        t51 = "HTML <html> tag";
        t52 = "HTML <i> tag";
        t53 = "HTML iframes";
        t54 = "HTML Image";
        t55 = "HTML Input Tag";
        t56 = "HTML <ins> tag";
        t57 = "HTML <isindex> tag";
        t58 = "HTML <kbd> tag";
        t59 = "HTML <label> tag";
        t60 = "HTML <legend> tag";
        t61 = "HTML Lists";
        t62 = "HTML <link> tag";
        t63 = "HTML Main Tag";
        t64 = "HTML <map> tag";
        t65 = "HTML <mark> tag";
        t66 = "HTML Marquee tag";
        t67 = "HTML <menu> tag";
        t68 = "HTML <meta> tag";
        t69 = "HTML Meter Tag";
        t70 = "HTML <nav> tag";
        t71 = "HTML <noframes> tag";
        t72 = "HTML NoScript Tag";
        t73 = "HTML <object> tag";
        t74 = "HTML Ordered List";
        t75 = "HTML <optgroup> tag";
        t76 = "HTML <option> tag";
        t77 = "HTML <output> tag";
        t78 = "HTML Paragraph";
        t79 = "HTML <param> tag";
        t80 = "HTML <picture> tag";
        t81 = "HTML pre tag";
        t82 = "HTML Progress Tag";
        t83 = "HTML Quotes";
        t84 = "HTML <rp> tag";
        t85 = "HTML <rt> tag";
        t86 = "HTML <ruby> tag";
        t87 = "HTML <s> tag";
        t88 = "HTML <samp> tag";
        t89 = "HTML Script Tag";
        t90 = "HTML Section Tag";
        t91 = "HTML <select> tag";
        t92 = "HTML <small> tag";
        t93 = "HTML <source> tag";
        t94 = "HTML <span> tag";
        t95 = "HTML <strike> tag";
        t96 = "HTML <strong> tag";
        t97 = "HTML Style";


        txt1  = findViewById(R.id.third_card1_heading);
        txt2  = findViewById(R.id.third_card2_heading);
        txt3  = findViewById(R.id.third_card3_heading);
        txt4  = findViewById(R.id.third_card4_heading);
        txt5  = findViewById(R.id.third_card5_heading);
        txt6  = findViewById(R.id.third_card6_heading);
        txt7  = findViewById(R.id.third_card7_heading);
        txt8  = findViewById(R.id.third_card8_heading);
        txt9  = findViewById(R.id.third_card9_heading);
        txt10  = findViewById(R.id.third_card10_heading);
        txt11  = findViewById(R.id.third_card11_heading);
        txt12  = findViewById(R.id.third_card12_heading);
        txt13  = findViewById(R.id.third_card13_heading);
        txt14  = findViewById(R.id.third_card14_heading);
        txt15  = findViewById(R.id.third_card15_heading);
        txt16  = findViewById(R.id.third_card16_heading);
        txt17  = findViewById(R.id.third_card17_heading);
        txt18  = findViewById(R.id.third_card18_heading);
        txt19  = findViewById(R.id.third_card19_heading);
        txt20  = findViewById(R.id.third_card20_heading);
        txt21  = findViewById(R.id.third_card21_heading);
        txt22  = findViewById(R.id.third_card22_heading);
        txt23  = findViewById(R.id.third_card23_heading);
        txt24  = findViewById(R.id.third_card24_heading);
        txt25  = findViewById(R.id.third_card25_heading);
        txt26  = findViewById(R.id.third_card26_heading);
        txt27  = findViewById(R.id.third_card27_heading);
        txt28  = findViewById(R.id.third_card28_heading);
        txt29  = findViewById(R.id.third_card29_heading);
        txt30  = findViewById(R.id.third_card30_heading);
        txt31  = findViewById(R.id.third_card31_heading);
        txt32  = findViewById(R.id.third_card32_heading);
        txt33  = findViewById(R.id.third_card33_heading);
        txt34  = findViewById(R.id.third_card34_heading);
        txt35  = findViewById(R.id.third_card35_heading);
        txt36  = findViewById(R.id.third_card36_heading);
        txt37  = findViewById(R.id.third_card37_heading);

        txt38  = findViewById(R.id.third_card38_heading);
        txt39  = findViewById(R.id.third_card39_heading);
        txt40  = findViewById(R.id.third_card40_heading);
        txt41  = findViewById(R.id.third_card41_heading);
        txt42  = findViewById(R.id.third_card42_heading);
        txt43  = findViewById(R.id.third_card43_heading);
        txt44  = findViewById(R.id.third_card44_heading);
        txt45  = findViewById(R.id.third_card45_heading);
        txt46  = findViewById(R.id.third_card46_heading);
        txt47  = findViewById(R.id.third_card47_heading);
        txt48  = findViewById(R.id.third_card48_heading);
        txt49  = findViewById(R.id.third_card49_heading);
        txt50  = findViewById(R.id.third_card50_heading);
        txt51  = findViewById(R.id.third_card51_heading);
        txt52  = findViewById(R.id.third_card52_heading);
        txt53  = findViewById(R.id.third_card53_heading);
        txt54  = findViewById(R.id.third_card54_heading);
        txt55  = findViewById(R.id.third_card55_heading);
        txt56  = findViewById(R.id.third_card56_heading);
        txt57  = findViewById(R.id.third_card57_heading);
        txt58  = findViewById(R.id.third_card58_heading);
        txt59  = findViewById(R.id.third_card59_heading);
        txt60  = findViewById(R.id.third_card60_heading);
        txt61  = findViewById(R.id.third_card61_heading);
        txt62  = findViewById(R.id.third_card62_heading);
        txt63  = findViewById(R.id.third_card63_heading);
        txt64  = findViewById(R.id.third_card64_heading);
        txt65  = findViewById(R.id.third_card65_heading);
        txt66  = findViewById(R.id.third_card66_heading);
        txt67  = findViewById(R.id.third_card67_heading);
        txt68  = findViewById(R.id.third_card68_heading);
        txt69  = findViewById(R.id.third_card69_heading);
        txt70  = findViewById(R.id.third_card70_heading);
        txt71  = findViewById(R.id.third_card71_heading);
        txt72  = findViewById(R.id.third_card72_heading);
        txt73  = findViewById(R.id.third_card73_heading);
        txt74  = findViewById(R.id.third_card74_heading);

        txt75  = findViewById(R.id.third_card75_heading);
        txt76  = findViewById(R.id.third_card76_heading);
        txt77  = findViewById(R.id.third_card77_heading);
        txt78  = findViewById(R.id.third_card78_heading);
        txt79  = findViewById(R.id.third_card79_heading);
        txt80  = findViewById(R.id.third_card80_heading);
        txt81  = findViewById(R.id.third_card81_heading);
        txt82  = findViewById(R.id.third_card82_heading);
        txt83  = findViewById(R.id.third_card83_heading);
        txt84  = findViewById(R.id.third_card84_heading);
        txt85  = findViewById(R.id.third_card85_heading);
        txt86  = findViewById(R.id.third_card86_heading);
        txt87  = findViewById(R.id.third_card87_heading);
        txt88  = findViewById(R.id.third_card88_heading);
        txt89  = findViewById(R.id.third_card89_heading);
        txt90  = findViewById(R.id.third_card90_heading);
        txt91  = findViewById(R.id.third_card91_heading);
        txt92  = findViewById(R.id.third_card92_heading);
        txt93  = findViewById(R.id.third_card93_heading);
        txt94  = findViewById(R.id.third_card94_heading);
        txt95  = findViewById(R.id.third_card95_heading);
        txt96  = findViewById(R.id.third_card96_heading);
        txt97  = findViewById(R.id.third_card97_heading);





        txt1.setText(t1);
        txt2.setText(t2);
        txt3.setText(t3);
        txt4.setText(t4);
        txt5.setText(t5);
        txt6.setText(t6);
        txt7.setText(t7);
        txt8.setText(t8);
        txt9.setText(t9);
        txt10.setText(t10);
        txt11.setText(t11);
        txt12.setText(t12);
        txt13.setText(t13);
        txt14.setText(t14);
        txt15.setText(t15);
        txt16.setText(t16);
        txt17.setText(t17);
        txt18.setText(t18);
        txt19.setText(t19);
        txt20.setText(t20);
        txt21.setText(t21);
        txt22.setText(t22);
        txt23.setText(t23);
        txt24.setText(t24);
        txt25.setText(t25);
        txt26.setText(t26);
        txt27.setText(t27);
        txt28.setText(t28);
        txt29.setText(t29);
        txt30.setText(t30);
        txt31.setText(t31);
        txt32.setText(t32);
        txt33.setText(t33);
        txt34.setText(t34);
        txt35.setText(t35);
        txt36.setText(t36);
        txt37.setText(t37);

        txt38.setText(t38);
        txt39.setText(t39);
        txt40.setText(t40);
        txt41.setText(t41);
        txt42.setText(t42);
        txt43.setText(t43);
        txt44.setText(t44);
        txt45.setText(t45);
        txt46.setText(t46);
        txt47.setText(t47);
        txt48.setText(t48);
        txt49.setText(t49);
        txt50.setText(t50);
        txt51.setText(t51);
        txt52.setText(t52);
        txt53.setText(t53);
        txt54.setText(t54);
        txt55.setText(t55);
        txt56.setText(t56);
        txt57.setText(t57);
        txt58.setText(t58);
        txt59.setText(t59);
        txt60.setText(t60);
        txt61.setText(t61);
        txt62.setText(t62);
        txt63.setText(t63);
        txt64.setText(t64);
        txt65.setText(t65);
        txt66.setText(t66);
        txt67.setText(t67);
        txt68.setText(t68);
        txt69.setText(t69);
        txt70.setText(t70);
        txt71.setText(t71);
        txt72.setText(t72);
        txt73.setText(t73);
        txt74.setText(t74);

        txt75.setText(t75);
        txt76.setText(t76);
        txt77.setText(t77);
        txt78.setText(t78);
        txt79.setText(t79);
        txt80.setText(t80);
        txt81.setText(t81);
        txt82.setText(t82);
        txt83.setText(t83);
        txt84.setText(t84);
        txt85.setText(t85);
        txt86.setText(t86);
        txt87.setText(t87);
        txt88.setText(t88);
        txt89.setText(t89);
        txt90.setText(t90);
        txt91.setText(t91);
        txt92.setText(t92);
        txt93.setText(t93);
        txt94.setText(t94);
        txt95.setText(t95);
        txt96.setText(t96);
        txt97.setText(t97);







        card1 = findViewById(R.id.third_card1);
        card2 = findViewById(R.id.third_card2);
        card3 = findViewById(R.id.third_card3);
        card4 = findViewById(R.id.third_card4);
        card5 = findViewById(R.id.third_card5);
        card6 = findViewById(R.id.third_card6);
        card7 = findViewById(R.id.third_card7);
        card8 = findViewById(R.id.third_card8);
        card9 = findViewById(R.id.third_card9);
        card10 = findViewById(R.id.third_card10);
        card11 = findViewById(R.id.third_card11);
        card12 = findViewById(R.id.third_card12);
        card13 = findViewById(R.id.third_card13);
        card14 = findViewById(R.id.third_card14);
        card15 = findViewById(R.id.third_card15);
        card16 = findViewById(R.id.third_card16);
        card17 = findViewById(R.id.third_card17);
        card18 = findViewById(R.id.third_card18);
        card19 = findViewById(R.id.third_card19);
        card20 = findViewById(R.id.third_card20);
        card21 = findViewById(R.id.third_card21);
        card22 = findViewById(R.id.third_card22);
        card23 = findViewById(R.id.third_card23);
        card24 = findViewById(R.id.third_card24);
        card25 = findViewById(R.id.third_card25);
        card26 = findViewById(R.id.third_card26);
        card27 = findViewById(R.id.third_card27);
        card28 = findViewById(R.id.third_card28);
        card29 = findViewById(R.id.third_card29);
        card30 = findViewById(R.id.third_card30);
        card31 = findViewById(R.id.third_card31);
        card32 = findViewById(R.id.third_card32);
        card33 = findViewById(R.id.third_card33);
        card34 = findViewById(R.id.third_card34);
        card35 = findViewById(R.id.third_card35);
        card36 = findViewById(R.id.third_card36);
        card37 = findViewById(R.id.third_card37);
        card38 = findViewById(R.id.third_card38);
        card39 = findViewById(R.id.third_card39);
        card40 = findViewById(R.id.third_card40);
        card41 = findViewById(R.id.third_card41);
        card42 = findViewById(R.id.third_card42);
        card43 = findViewById(R.id.third_card43);
        card44 = findViewById(R.id.third_card44);
        card45 = findViewById(R.id.third_card45);
        card46 = findViewById(R.id.third_card46);
        card47 = findViewById(R.id.third_card47);
        card48 = findViewById(R.id.third_card48);
        card49 = findViewById(R.id.third_card49);
        card50 = findViewById(R.id.third_card50);
        card51 = findViewById(R.id.third_card51);
        card52 = findViewById(R.id.third_card52);
        card53 = findViewById(R.id.third_card53);
        card54 = findViewById(R.id.third_card54);
        card55 = findViewById(R.id.third_card55);
        card56 = findViewById(R.id.third_card56);
        card57 = findViewById(R.id.third_card57);
        card58 = findViewById(R.id.third_card58);
        card59 = findViewById(R.id.third_card59);
        card60 = findViewById(R.id.third_card60);
        card61 = findViewById(R.id.third_card61);
        card62 = findViewById(R.id.third_card62);
        card63 = findViewById(R.id.third_card63);
        card64 = findViewById(R.id.third_card64);
        card65 = findViewById(R.id.third_card65);
        card66 = findViewById(R.id.third_card66);
        card67 = findViewById(R.id.third_card67);
        card68 = findViewById(R.id.third_card68);
        card69 = findViewById(R.id.third_card69);
        card70 = findViewById(R.id.third_card70);
        card71 = findViewById(R.id.third_card71);
        card72 = findViewById(R.id.third_card72);
        card73 = findViewById(R.id.third_card73);
        card74 = findViewById(R.id.third_card74);
        card75 = findViewById(R.id.third_card75);
        card76 = findViewById(R.id.third_card76);
        card77 = findViewById(R.id.third_card77);
        card78 = findViewById(R.id.third_card78);
        card79 = findViewById(R.id.third_card79);
        card80 = findViewById(R.id.third_card80);
        card81 = findViewById(R.id.third_card81);
        card82 = findViewById(R.id.third_card82);
        card83 = findViewById(R.id.third_card83);
        card84 = findViewById(R.id.third_card84);
        card85 = findViewById(R.id.third_card85);
        card86 = findViewById(R.id.third_card86);
        card87 = findViewById(R.id.third_card87);
        card88 = findViewById(R.id.third_card88);
        card89 = findViewById(R.id.third_card89);
        card90 = findViewById(R.id.third_card90);
        card91 = findViewById(R.id.third_card91);
        card92 = findViewById(R.id.third_card92);
        card93 = findViewById(R.id.third_card93);
        card94 = findViewById(R.id.third_card94);
        card95 = findViewById(R.id.third_card95);
        card96 = findViewById(R.id.third_card96);
        card97 = findViewById(R.id.third_card97);


        file1  = "file:///android_asset/html_doctype_tag.html";
        file2  = "file:///android_asset/html_anchor_tag.html";
        file3  = "file:///android_asset/html_abbr_tag.html";
        file4  = "file:///android_asset/html_acronym_tag.html";
        file5  = "file:///android_asset/html_address_tag.html";
        file6  = "file:///android_asset/html_applet_tag.html";
        file7  = "file:///android_asset/html_area_tag.html";
        file8  = "file:///android_asset/html_article_tag.html";
        file9  = "file:///android_asset/html_aside_tag.html";
        file10 = "file:///android_asset/html_audio_tag.html";
        file11 = "file:///android_asset/html_bold_tag.html";
        file12 = "file:///android_asset/html_base_tag.html";
        file13 = "file:///android_asset/html_basefont_tag.html";
        file14 = "file:///android_asset/html_bdi_tag.html";
        file15 = "file:///android_asset/html_bdo_tag.html";
        file16 = "file:///android_asset/html_big_tag.html";
        file17 = "file:///android_asset/html_blockquote_tag.html";
        file18 = "file:///android_asset/html_body_tag.html";
        file19 = "file:///android_asset/html_br_tag.html";
        file20 = "file:///android_asset/html_button_tag.html";
        file21 = "file:///android_asset/html_canvas_tag.html";
        file22 = "file:///android_asset/html_caption_tag.html";
        file23 = "file:///android_asset/html_center_tag.html";
        file24 = "file:///android_asset/html_cite_tag.html";
        file25 = "file:///android_asset/html_code_tag.html";
        file26 = "file:///android_asset/html_col_tag.html";
        file27 = "file:///android_asset/html_colgroup_tag.html";
        file28 = "file:///android_asset/html_data_tag.html";
        file29 = "file:///android_asset/html_datalist_tag.html";
        file30 = "file:///android_asset/html_description_tag.html";
        file31 = "file:///android_asset/html_del_tag.html";
        file32 = "file:///android_asset/html_details_tag.html";
        file33 = "file:///android_asset/html_dfn_tag.html";
        file34 = "file:///android_asset/html_dialog_tag.html";
        file35 = "file:///android_asset/html_dir_tag.html";
        file36 = "file:///android_asset/html_div_tag.html";
        file37 = "file:///android_asset/html_em_tag.html";
        file38 = "file:///android_asset/html_embed_tag.html";
        file39 = "file:///android_asset/html_fieldset_tag.html";
        file40 = "file:///android_asset/html_figcaption_tag.html";
        file41 = "file:///android_asset/html_figure_tag.html";
        file42 = "file:///android_asset/html_font_tag.html";
        file43 = "file:///android_asset/html_footer_tag.html";
        file44 = "file:///android_asset/html_form_tag.html";
        file45 = "file:///android_asset/html_frame_tag.html";
        file46 = "file:///android_asset/html_frameset_tag.html";
        file47 = "file:///android_asset/html_heading_tag.html";
        file48 = "file:///android_asset/html_head_tag.html";
        file49 = "file:///android_asset/html_header_tag.html";
        file50 = "file:///android_asset/html_hr_tag.html";
        file51 = "file:///android_asset/html_html_tag.html";
        file52 = "file:///android_asset/html_i_tag.html";
        file53 = "file:///android_asset/html_iframe_tag.html";
        file54 = "file:///android_asset/html_image_tag.html";
        file55 = "file:///android_asset/html_input_tag.html";
        file56 = "file:///android_asset/html_ins_tag.html";
        file57 = "file:///android_asset/html_isindex_tag.html";
        file58 = "file:///android_asset/html_kbd_tag.html";
        file59 = "file:///android_asset/html_label_tag.html";
        file60 = "file:///android_asset/html_legend_tag.html";
        file61 = "file:///android_asset/html_list_tag.html";
        file62 = "file:///android_asset/html_link_tag.html";
        file63 = "file:///android_asset/html_main_tag.html";
        file64 = "file:///android_asset/html_map_tag.html";
        file65 = "file:///android_asset/html_mark_tag.html";
        file66 = "file:///android_asset/html_marquee_tag.html";
        file67 = "file:///android_asset/html_menu_tag.html";
        file68 = "file:///android_asset/html_meta_tag.html";
        file69 = "file:///android_asset/html_meter_tag.html";
        file70 = "file:///android_asset/html_nav_tag.html";
        file71 = "file:///android_asset/html_noframes_tag.html";
        file72 = "file:///android_asset/html_noscript_tag.html";
        file73 = "file:///android_asset/html_object_tag.html";
        file74 = "file:///android_asset/html_ordered_list_tag.html";
        file75 = "file:///android_asset/html_optgroup_tag.html";
        file76 = "file:///android_asset/html_option_tag.html";
        file77 = "file:///android_asset/html_output_tag.html";
        file78 = "file:///android_asset/html_paragraph_tag.html";
        file79 = "file:///android_asset/html_param_tag.html";
        file80 = "file:///android_asset/html_picture_tag.html";
        file81 = "file:///android_asset/html_pre_tag.html";
        file82 = "file:///android_asset/html_progress_tag.html";
        file83 = "file:///android_asset/html_quotes_tag.html";
        file84 = "file:///android_asset/html_rp_tag.html";
        file85 = "file:///android_asset/html_rt_tag.html";
        file86 = "file:///android_asset/html_ruby_tag.html";
        file87 = "file:///android_asset/html_s_tag.html";
        file88 = "file:///android_asset/html_samp_tag.html";
        file89 = "file:///android_asset/html_script_tag.html";
        file90 = "file:///android_asset/html_section_tag.html";
        file91 = "file:///android_asset/html_select_tag.html";
        file92 = "file:///android_asset/html_small_tag.html";
        file93 = "file:///android_asset/html_source_tag.html";
        file94 = "file:///android_asset/html_span_tag.html";
        file95 = "file:///android_asset/html_strike_tag.html";
        file96 = "file:///android_asset/html_strong_tag.html";
        file97 = "file:///android_asset/html_style_tag.html";




        contentIntent(card1 ,file1 ,t1 );
        contentIntent(card2 ,file2 ,t2 );
        contentIntent(card3 ,file3 ,t3 );
        contentIntent(card4 ,file4 ,t4 );
        contentIntent(card5 ,file5 ,t5 );
        contentIntent(card6 ,file6 ,t6 );
        contentIntent(card7 ,file7 ,t7 );
        contentIntent(card8 ,file8 ,t8 );
        contentIntent(card9 ,file9 ,t9 );
        contentIntent(card10,file10,t10);
        contentIntent(card11,file11,t11);
        contentIntent(card12,file12,t12);
        contentIntent(card13,file13,t13);
        contentIntent(card14,file14,t14);
        contentIntent(card15,file15,t15);
        contentIntent(card16,file16,t16);
        contentIntent(card17,file17,t17);
        contentIntent(card18,file18,t18);
        contentIntent(card19,file19,t19);
        contentIntent(card20,file20,t20);
        contentIntent(card21,file21,t21);
        contentIntent(card22,file22,t22);
        contentIntent(card23,file23,t23);
        contentIntent(card24,file24,t24);
        contentIntent(card25,file25,t25);
        contentIntent(card26,file26,t26);
        contentIntent(card27,file27,t27);
        contentIntent(card28,file28,t28);
        contentIntent(card29,file29,t29);
        contentIntent(card30,file30,t30);
        contentIntent(card31,file31,t31);
        contentIntent(card32,file32,t32);
        contentIntent(card33,file33,t33);
        contentIntent(card34,file34,t34);
        contentIntent(card35,file35,t35);
        contentIntent(card36,file36,t36);
        contentIntent(card37,file37,t37);
        contentIntent(card38,file38,t38);
        contentIntent(card39,file39,t39);
        contentIntent(card40,file40,t40);
        contentIntent(card41,file41,t41);
        contentIntent(card42,file42,t42);
        contentIntent(card43,file43,t43);
        contentIntent(card44,file44,t44);
        contentIntent(card45,file45,t45);
        contentIntent(card46,file46,t46);
        contentIntent(card47,file47,t47);
        contentIntent(card48,file48,t48);
        contentIntent(card49,file49,t49);
        contentIntent(card50,file50,t50);
        contentIntent(card51,file51,t51);
        contentIntent(card52,file52,t52);
        contentIntent(card53,file53,t53);
        contentIntent(card54,file54,t54);
        contentIntent(card55,file55,t55);
        contentIntent(card56,file56,t56);
        contentIntent(card57,file57,t57);
        contentIntent(card58,file58,t58);
        contentIntent(card59,file59,t59);
        contentIntent(card60,file60,t60);
        contentIntent(card61,file61,t61);
        contentIntent(card62,file62,t62);
        contentIntent(card63,file63,t63);
        contentIntent(card64,file64,t64);
        contentIntent(card65,file65,t65);
        contentIntent(card66,file66,t66);
        contentIntent(card67,file67,t67);
        contentIntent(card68,file68,t68);
        contentIntent(card69,file69,t69);
        contentIntent(card70,file70,t70);
        contentIntent(card71,file71,t71);
        contentIntent(card72,file72,t72);
        contentIntent(card73,file73,t73);
        contentIntent(card74,file74,t74);
        contentIntent(card75,file75,t75);
        contentIntent(card76,file76,t76);
        contentIntent(card77,file77,t77);
        contentIntent(card78,file78,t78);
        contentIntent(card79,file79,t79);
        contentIntent(card80,file80,t80);
        contentIntent(card81,file81,t81);
        contentIntent(card82,file82,t82);
        contentIntent(card83,file83,t83);
        contentIntent(card84,file84,t84);
        contentIntent(card85,file85,t85);
        contentIntent(card86,file86,t86);
        contentIntent(card87,file87,t87);
        contentIntent(card88,file88,t88);
        contentIntent(card89,file89,t89);
        contentIntent(card90,file90,t90);
        contentIntent(card91,file91,t91);
        contentIntent(card92,file92,t92);
        contentIntent(card93,file93,t93);
        contentIntent(card94,file94,t94);
        contentIntent(card95,file95,t95);
        contentIntent(card96,file96,t96);
        contentIntent(card97,file97,t97);






    }
    @Override
    public boolean onOptionsItemSelected(@NonNull MenuItem item) {
        super.onBackPressed();
        return super.onOptionsItemSelected(item);
    }

    public void contentIntent(CardView card, String file, String title){
        card.setOnClickListener(v -> {
            Intent webIntent = new Intent(card3_activity.this, card1_content.class);
            webIntent.putExtra("file",file);
            webIntent.putExtra("title",title);
            startActivity(webIntent);
        });
    }
}